default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     fr
    #robots:       index, follow

  stylesheets:    [main.css, sredmond/jquery-ui-1.8.9.custom.css, detail.css, listing.css, abusif.css]

  javascripts:    [jquery-1.5.min.js, jquery-ui-1.8.9.custom.min.js, detail.js]

  has_layout:     on
  layout:         layout
  