sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
      
en_display_ad:
  url:     /display-ad/:id/:region_slug/:departement_slug/:slug
  class:   sfDoctrineRoute
  options: { model: Annonce, type: object }
  param:   { module: detail, action: index }
  requirements:
    id: \d+

fr_display_ad:
  url:     /voir-annonce/:region_slug/:departement_slug/:id/:annonce_slug
  class:   sfDoctrineRoute
  options: { model: Annonce, type: object }
  param:   { module: detail, action: index }
  requirements:
    id: \d+

en_ads_validation:
  url:   /ads-validation
  param: { module: controle, action: index }
    
fr_ads_validation:
  url:   /validation-annonce
  param: { module: controle, action: index }

en_my_ads:
  url:   /my-ads
  param: { module: mes_annonces_light, action: index }
    
fr_my_ads:
  url:   /mes-annonces
  param: { module: mes_annonces_light, action: index }
      
en_ads:
  url:   /ads
  param: { module: listing, action: index }
    
fr_ads:
  url:   /annonces
  param: { module: listing, action: index }
  
en_ad_demand:
  url:   /ads/demands
  param: { module: listing, action: demandes }
    
fr_ad_demand:
  url:   /annonces/demandes
  param: { module: listing, action: demandes }
  
en_ad_offer:
  url:   /ads/offers
  param: { module: listing, action: offres }
    
fr_ad_offer:
  url:   /annonces/offres
  param: { module: listing, action: offres }
    
en_delete_picture:
  url:   /ad/delete-picture
  param: { module: postAd, action: deletePicture }
  requirements:
    sf_method: [get]
    
fr_delete_picture:
  url:   /supprimer-une-photo
  param: { module: postAd, action: deletePicture }
  requirements:
    sf_method: [get]
    
en_thankyou_ad:
  url:   /ad/thankyou
  param: { module: postAd, action: thankyou }
  requirements:
    sf_method: [get]
  
fr_thankyou_ad:
  url:   /merci-pour-le-depot
  param: { module: postAd, action: thankyou }
  requirements:
    sf_method: [get]
    
en_edit_ad:
  url:   /ad/edit
  param: { module: postAd, action: new }
  requirements:
    sf_method: [get]
  
fr_edit_ad:
  url:   /modifier-une-annonce
  param: { module: postAd, action: new }
  requirements:
    sf_method: [get]
  
en_review_ad:
  url:   /ad/review
  param: { module: postAd, action: review }
  
fr_review_ad:
  url:   /deposer-une-annonce/verifier
  param: { module: postAd, action: review }
  
en_post_ad:
  url:   /ad/post
  param: { module: postAd, action: new }

fr_post_ad:
  url:   /deposer-une-annonce
  param: { module: postAd, action: new }
    
en_post_ad_create:
  url:   /ad/post
  param: { module: postAd, action: new }
  
fr_post_ad_create:
  url:   /deposer-une-annonce
  param: { module: postAd, action: new }

en_post_ad_update:
  url:   /ad/post
  param: { module: postAd, action: new }
  
fr_post_ad_update:
  url:   /deposer-une-annonce
  param: { module: postAd, action: new }

# default rules
homepage:
  url:   /
  param: { module: accueil, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
