Administrateur:
  tableName: administrateur
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nom:
      type: string(50)
      notnull: true
    prenom:
      type: string(20)
      notnull: true
    mail:
      type: string(100)
      notnull: true
    mdp:
      type: string(20)
      notnull: true
  relations:
    Annonce:
      local: id
      foreign: validee_par
      type: many
    Annonce_7:
      class: Annonce
      local: id
      foreign: validee_par
      type: many
Annonce:
  tableName: annonce
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    etat_de_validation:
      type: enum(8)
      values: [wait, accepted, rejected]
      default: wait
    ville:
      type: string(30)
      notnull: true
    code_postal:
      type: string(5)
      notnull: true
    contenu:
      type: string(1024)
      notnull: true
    titre:
      type: string(50)
      notnull: true
    prix:
      type: decimal(65)
      scale: false
    est_abusif:
      type: integer(4)
      default: '0'
    type_annonce:
      type: enum(7)
      values: [offre, demande]
      notnull: true
    categorie:
      type: integer(4)
      notnull: true
    region:
      type: integer(4)
      notnull: true
    departement:
      type: integer(4)
      notnull: true
    telephone: string(10)
    annonceur: integer(4)
    validee_par: integer(4)
    date_control: timestamp(25)
  relations:
    Administrateur:
      local: validee_par
      foreign: id
      type: one
    Annonceur:
      local: annonceur
      foreign: id
      type: one
    Region:
      local: region
      foreign: id
      type: one
    Departement:
      local: departement
      foreign: code_dep
      type: one
    Categorie:
      local: categorie
      foreign: id
      type: one
    Annonceur_6:
      class: Annonceur
      local: annonceur
      foreign: id
      type: one
    Administrateur_7:
      class: Administrateur
      local: validee_par
      foreign: id
      type: one
    Region_8:
      class: Region
      local: region
      foreign: id
      type: one
    Departement_9:
      class: Departement
      local: departement
      foreign: code_dep
      type: one
    Categorie_10:
      class: Categorie
      local: categorie
      foreign: id
      type: one
Annonceur:
  tableName: annonceur
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    mail:
      type: string(100)
      notnull: true
    mdp:
      type: string(20)
      notnull: true
  relations:
    Annonce:
      local: id
      foreign: annonceur
      type: many
    Annonce_6:
      class: Annonce
      local: id
      foreign: annonceur
      type: many
Categorie:
  tableName: categorie
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nom:
      type: string(200)
      notnull: true
  relations:
    Annonce:
      local: id
      foreign: categorie
      type: many
    Annonce_10:
      class: Annonce
      local: id
      foreign: categorie
      type: many
Departement:
  tableName: departement
  columns:
    code_dep:
      type: integer(4)
      primary: true
    nom:
      type: string(255)
      notnull: true
    region:
      type: integer(4)
      default: '0'
      notnull: true
  relations:
    Region:
      local: region
      foreign: id
      type: one
    Region_2:
      class: Region
      local: region
      foreign: id
      type: one
    Annonce:
      local: code_dep
      foreign: departement
      type: many
    Annonce_9:
      class: Annonce
      local: code_dep
      foreign: departement
      type: many
Region:
  tableName: region
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nom:
      type: string(100)
      notnull: true
  relations:
    Annonce:
      local: id
      foreign: region
      type: many
    Annonce_8:
      class: Annonce
      local: id
      foreign: region
      type: many
    Departement:
      local: id
      foreign: region
      type: many
    Departement_2:
      class: Departement
      local: id
      foreign: region
      type: many
