annonce_annonce:
  class: sfDoctrineRouteCollection
  options:
    model:                Annonce
    module:               annonce
    prefix_path:          annonce
    column:               id
    with_wildcard_routes: true

administrateur_administrateur:
  class: sfDoctrineRouteCollection
  options:
    model:                Administrateur
    module:               administrateur
    prefix_path:          administrateur
    column:               id
    with_wildcard_routes: true

annonceur_annonceur:
  class: sfDoctrineRouteCollection
  options:
    model:                Annonceur
    module:               annonceur
    prefix_path:          annonceur
    column:               id
    with_wildcard_routes: true

categorie_categorie:
  class: sfDoctrineRouteCollection
  options:
    model:                Categorie
    module:               categorie
    prefix_path:          categorie
    column:               id
    with_wildcard_routes: true

departement_departement:
  class: sfDoctrineRouteCollection
  options:
    model:                Departement
    module:               departement
    prefix_path:          departement
    column:               code_dep
    with_wildcard_routes: true

region_region:
  class: sfDoctrineRouteCollection
  options:
    model:                Region
    module:               region
    prefix_path:          region
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
