Administrateur:
  tableName: administrateur
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nom:
      type: string(50)
      notnull: true
    prenom:
      type: string(20)
      notnull: true
    mail:
      type: string(100)
      notnull: true
    mdp:
      type: string(20)
      notnull: true
  relations:
    Annonce:
      local: id
      foreign: validee_par
      type: many
Annonce:
  tableName: annonce
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    etat_de_validation:
      type: string(8)
      default: wait
    nom_annonceur: string(20)
    ville:
      type: string(30)
      notnull: true
    code_postal:
      type: string(5)
      notnull: true
    contenu:
      type: string()
      notnull: true
    titre:
      type: string(50)
      notnull: true
    prix:
      type: decimal(65)
      scale: false
    est_abusif:
      type: integer(4)
      default: '0'
    type_annonce:
      type: enum
      values: [offre, demande]
      notnull: true
    categorie:
      type: integer(4)
      notnull: true
    region:
      type: integer(4)
      notnull: true
    departement:
      type: integer(4)
      notnull: true
    telephone: string(10)
    annonceur: integer(4)
    validee_par: integer(4)
    date_control: timestamp(25)
    pays: 
      type: string(2)
      fixed: true
  relations:
    Administrateur:
      local: validee_par
      foreign: id
      type: one
    Region:
      local: region
      foreign: id
      type: one
    Departement:
      local: departement
      foreign: code_dep
      type: one
    Categorie:
      local: categorie
      foreign: id
      type: one
    Annonceur:
      local: annonceur
      foreign: id
      type: one
    AnnoncePhoto:
      local: id
      foreign: annonce_id
      type: many
AnnoncePhoto:
  tableName: annonce_photo
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    annonce_id: integer(4)
    filename: string(255)
  relations:
    Annonce:
      local: annonce_id
      foreign: id
      type: one
Annonceur:
  tableName: annonceur
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    sf_guard_user_id:
      type: integer(4)
      notnull: true
    type_annonceur: string(12) #individual or professional
  relations:
    sfGuardUser:
      local: sf_guard_user_id
      foreign: id
      foreignType: one
      onDelete: cascade
    Annonce:
      local: id
      foreign: annonceur
      type: many
Categorie:
  actAs:
    I18n:
      fields: [nom]
  tableName: categorie
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nom:
      type: string(200)
      notnull: true
  relations:
    Annonce:
      local: id
      foreign: categorie
      type: many
CodePostaux:
  tableName: code_postaux
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    commune:
      type: string(50)
      notnull: true
    codepos:
      type: string(5)
      fixed: true
      notnull: true
    departement:
      type: string(50)
      notnull: true
    insee:
      type: string(10)
      notnull: true
Departement:
  tableName: departement
  columns:
    code_dep:
      type: integer(4)
      primary: true
    nom:
      type: string(255)
      notnull: true
    region:
      type: integer(4)
      default: '0'
      notnull: true
    pays:
      type: string(2)
      fixed: true
  relations:
    Region:
      local: region
      foreign: id
      type: one
    Annonce:
      local: code_dep
      foreign: departement
      type: many
Region:
  tableName: region
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nom:
      type: string(100)
      notnull: true
    pays:
      type: string(2)
      fixed: true
  relations:
    Annonce:
      local: id
      foreign: region
      type: many
    Departement:
      local: id
      foreign: region
      type: many